# Build Jekyll configuration
# These settings override _config.yml on `grunt build`

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

baseurl: http://webworke.rs

# Publish posts with future date.
future: false

# Compile posts in the _drafts directory.
show_drafts: false
