# Jekyll configuration
# Use _config.build.yml to override these settings on `grunt build`.

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

title: Webworke.rs
baseurl: http://127.0.0.1:9000
tagline: Life and Craft in Columbus, Ohio
description: This is the site description
twitter: Webwrkrs
facebook: https://www.facebook.com/webworkers
tumblr: http://webwrkrs.tumblr.com
feed: /feed.xml
newsletter: http://path/to/newsletter
analytics: UA-26697016-1

author:
  name: David Ensinger
  email: david@webworke.rs
  github: davidensinger
  twitter: DavidEnsinger

relative_permalinks: false

permalink: /:year/:month/:title/
paginate: 5

# Use redcarpet for jekyll-picture-tag plugin
markdown: redcarpet

exclude: ['assets/images', 'assets/styles', 'assets/scripts', 'assets/fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.svg', '**.ico']

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Use Pygments to highlight code blocks
pygments: false

# https://github.com/robwierzbowski/jekyll-picture-tag
picture:
  source: assets/images/_fullsize
  output: generated
  markup: "picturefill"
  presets:
    default:
      ppi: [1, 1.5]
      source_small-mobile:
        media: "(max-width: 320px)"
        width: 320
      source_mobile-portrait-to-mobile-landscape:
        media: "(max-width: 479px)"
        width: 479
      source_all-mobile:
        media: "(max-width: 767px)"
        width: 767
      source_smaller-than-small-desktop:
        media: "(max-width: 959px)"
        width: 959
      source_default:
        width: 1280
    sidebar:
      ppi: [1, 1.5]
      attr:
        class: "image sidebar--image"
        itemprop: "contentURL"
      source_small-mobile:
        media: "(max-width: 320px)"
        width: 320
      source_mobile-portrait-to-mobile-landscape:
        media: "(max-width: 479px)"
        width: 479
      source_default:
        width: 320
    image--3-4:
      ppi: [1, 1.5]
      source_small-mobile:
        media: "(max-width: 320px)"
        width: 320
      source_mobile-portrait-to-mobile-landscape:
        media: "(max-width: 479px)"
        width: 479
      source_desktop:
        media: "(min-width: 1281px)"
        width: 959
      source_default:
        width: 767
    image--2-3:
      ppi: [1, 1.5]
      source_small-mobile:
        media: "(max-width: 320px)"
        width: 320
      source_all-mobile:
        media: "(max-width: 767px)"
        width: 479
      source_default:
        width: 767
    image--1-2:
      ppi: [1, 1.5]
      source_small-mobile:
        media: "(max-width: 320px)"
        width: 320
      source_smaller-than-small-desktop:
        media: "(max-width: 959px)"
        width: 479
      source_default:
        width: 767
    image--1-3:
      ppi: [1, 1.5]
      source_small-mobile:
        media: "(max-width: 320px)"
        width: 320
      source_mobile-portrait-to-mobile-landscape:
        media: "(max-width: 479px)"
        width: 479
      source_smaller-than-small-desktop:
        media: "(max-width: 959px)"
        width: 320
      source_default:
        width: 479
    image--1-4:
      ppi: [1, 1.5]
      source_small-mobile:
        media: "(max-width: 320px)"
        width: 320
      source_mobile-portrait-to-mobile-landscape:
        media: "(max-width: 479px)"
        width: 479
      source_default:
        width: 320
