# Jekyll configuration
# Use _config.build.yml to override these settings on `grunt build`.

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

title: Webworke.rs
baseurl: http://127.0.0.1:9000
tagline: Life and Craft in Columbus, Ohio
description: This is the site description
twitter: Webwrkrs
facebook: https://www.facebook.com/webworkers
tumblr: http://webwrkrs.tumblr.com
feed: /feed.xml
newsletter: http://path/to/newsletter

author:
  name: David Ensinger
  email: david@webworke.rs
  github: davidensinger
  twitter: DavidEnsinger

relative_permalinks: false

permalink: /:year/:month/:title/
paginate: 5

exclude: ['assets/images', 'assets/styles', 'assets/scripts', 'assets/fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.svg']

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

# Use Pygments to highlight code blocks
pygments: false
