# Jekyll configuration
# Use _config.build.yml to override these settings on `grunt build`.

# Note: Grunt handles some Jekyll configuration. If you set something here and
# it doesn't work, check if it is set in the Gruntfile.

title: Webworke.rs
url: http://127.0.0.1:9000
tagline: Life and Craft in Columbus, OH
description: Webworke.rs is a website about folks who make websites in Columbus, OH.
analytics: UA-26697016-1

# social
facebook: https://www.facebook.com/Webworkers614
feed: /feed.xml
github: https://github.com/davidensinger/webworke.rs
googleplus: https://plus.google.com/+Webworkers614/
linkedin: huh
newsletter: http://eepurl.com/NGW5j
tumblr: http://Webworkers614.tumblr.com
twitter: Webworkers614

author:
  name: David Ensinger
  email: david@webworke.rs
  github: davidensinger
  twitter: DavidEnsinger
  googleplus: 111951762509840042073

exclude: ['images', 'styles', 'scripts', 'fonts', '**.png', '**.jpg', '**.jpeg', '**.gif', '**.svg', '**.ico']

# Publish posts with future date.
# _config.build.yml sets this to false on `grunt build`
future: true

# Compile posts in the _drafts directory.
# _config.build.yml sets this to false on `grunt build`
show_drafts: true

permalink: /:year/:month/:title/
relative_permalinks: false

category_title_prefix: ''
category_dir: /

paginate: 999
paginate_path: 'page:num'

# disable this with ''
excerpt_separator: ''

# Use Pygments to highlight code blocks
highlighter: pygments

# Use redcarpet for jekyll-picture-tag plugin
markdown: redcarpet

# https://github.com/robwierzbowski/jekyll-picture-tag
# Note that I’ve reduced the number of presets to decrease the build time
# while doing development. See _config.build.yml for further presets.
picture:
  source: images/originals
  output: generated
  markup: picture
  presets:
    default:
      ppi: [1]
      source_default:
        width: 1280
    sidebar:
      ppi: [1]
      attr:
        class: 'image sidebar-image'
        itemprop: 'contentURL'
      source_default:
        width: 479
    image--3-4:
      ppi: [1]
      source_default:
        width: 959
    image--2-3:
      ppi: [1]
      source_default:
        width: 767
    image--1-2:
      ppi: [1]
      source_default:
        width: 767
    image--1-3:
      ppi: [1]
      source_default:
        width: 479
    image--1-4:
      ppi: [1]
      source_default:
        width: 479
